# Generated by Django 3.2.12 on 2023-02-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Short',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_url', models.URLField(verbose_name='기본URL')),
                ('short_url', models.CharField(max_length=30, verbose_name='URL 단축값')),
            ],
        ),
    ]
