# Generated by Django 3.2.12 on 2023-02-26 04:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short',
            name='full_url',
            field=models.URLField(validators=[django.core.validators.URLValidator], verbose_name='기본URL'),
        ),
        migrations.AlterField(
            model_name='short',
            name='short_url',
            field=models.CharField(max_length=30, unique=True, verbose_name='URL 단축값'),
        ),
    ]
